version: '3'

services:
  app:
    #image: robsantossilva/laravel-optmized
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app_data/env.tpl:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    #entrypoint: dockerize -template ./.docker/app/.env:.env ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    # volumes:
    #   - .:/var/www
    networks:
      - app-network
    depends_on: 
      - db
      - redis
  nginx:
    build: .docker/nginx
    container_name: nginx
    entrypoint: dockerize -template ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    command: [nginx, '-g', 'daemon off;']
    environment:
      - APP_HOST=app
      - APP_PORT=9000
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes: 
      - .:/var/www
    networks:
      - app-network
    depends_on: 
      - app
  db:
    build: .docker/mysql
    container_name: db
    command: --innodb-use-native-aio=0
    #restart: always
    tty: true
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge